files:
    include: scss/*.scss
rules:
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    indentation:
        - 2
        -
            size: 4
    nesting-depth: 0
    no-qualifying-elements: 0
    no-url-domains: 0
    no-url-protocols: 0
