language: node_js
node_js:
    - "4.2.6"
addons:
    apt:
        packages:
            - ruby
before_install:
    - npm install -g grunt-cli
    - gem install --no-ri compass
    - gem install --no-ri scss-lint
install:
    - npm install
script:
    - mkdir -p dist
    - grunt
    - cp index.html dist
    - cp logo.png dist
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master
    local_dir: dist
